spring:
  application:
    name: PRODUCT-SERVICE

server:
  port: 8083

#Eureka/Registry/Discovery Client Config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true